server:
  port: ${random.int[20100,20101]}


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.sunnly.wang:3306/sunnly-oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: sunnly
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


#  禁用默认的http，启用okhttp
feign:
  sentinel:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true

sunnly:
  path-patterns:
    client:
      intercept:
        - /intercept/client/**
      exclude:
        - /intercept/client/pass
    user:
      intercept:
        - /intercept/user/**
        - /test/**
      exclude:
        - /intercept/user/pass

  security:
    auth:
      service-id: sunnly-micro-security-oauth
      client:
        id: ace-admin
        secret: 123456
        token-header: x-client-token
      user:
        token-header: Authorization